// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class Status {
    /**
     * Creates a new Status instance.
     * @param {Partial<Status>} [$$source = {}] - The source object to create the Status.
     */
    constructor($$source = {}) {
        if (!("running" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["running"] = false;
        }
        if (!("starting" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["starting"] = false;
        }
        if (!("attached" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["attached"] = false;
        }
        if (!("port" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["port"] = 0;
        }
        if (!("url" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["url"] = "";
        }
        if (!("pid" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["pid"] = 0;
        }
        if (!("binaryPath" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["binaryPath"] = "";
        }
        if (!("dataDir" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["dataDir"] = "";
        }
        if (!("health" in $$source)) {
            /**
             * @member
             * @type {{ [_ in string]?: any }}
             */
            this["health"] = {};
        }
        if (!("lastError" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["lastError"] = "";
        }
        if (!("logs" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["logs"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Status instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Status}
     */
    static createFrom($$source = {}) {
        const $$createField8_0 = $$createType0;
        const $$createField10_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("health" in $$parsedSource) {
            $$parsedSource["health"] = $$createField8_0($$parsedSource["health"]);
        }
        if ("logs" in $$parsedSource) {
            $$parsedSource["logs"] = $$createField10_0($$parsedSource["logs"]);
        }
        return new Status(/** @type {Partial<Status>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = $Create.Map($Create.Any, $Create.Any);
const $$createType1 = $Create.Array($Create.Any);
