<template>
  <v-dialog :model-value="show" max-width="800" persistent @update:model-value="$emit('update:show', $event)">
    <v-card rounded="lg" class="add-channel-dialog">
      <v-card-title class="d-flex align-center ga-3 pa-6" :class="headerClasses">
        <v-avatar :color="avatarColor" variant="flat" size="40">
          <v-icon :style="headerIconStyle" size="20">mdi-plus</v-icon>
        </v-avatar>
        <div class="flex-grow-1 modal-header-text">
          <div class="modal-title">
            {{ t('addChannel.createTitle') }}
          </div>
          <div class="modal-subtitle" :class="subtitleClasses">
            {{ t('addChannel.quickSubtitle') }}
          </div>
        </div>
      </v-card-title>

      <v-card-text class="pa-6">
        <div class="d-flex flex-column ga-3">
          <v-textarea
            v-model="quickInput"
            :label="t('addChannel.quickInputLabel')"
            :placeholder="t('addChannel.quickInputPlaceholder')"
            variant="outlined"
            rows="10"
            no-resize
            autofocus
            class="quick-input-textarea"
            @input="parseQuickInput"
          />

          <v-card variant="outlined" class="detection-status-card" rounded="lg">
            <v-card-text class="pa-4">
              <div class="d-flex flex-column ga-3">
                <div class="d-flex align-start ga-3">
                  <v-icon :color="detectedBaseUrls.length > 0 ? 'success' : 'error'" size="20" class="mt-1">
                    {{ detectedBaseUrls.length > 0 ? 'mdi-check-circle' : 'mdi-alert-circle' }}
                  </v-icon>
                  <div class="flex-grow-1">
                    <div class="text-body-2 font-weight-medium">{{ t('addChannel.baseUrl') }}</div>
                    <div v-if="detectedBaseUrls.length === 0" class="text-caption text-error">
                      {{ t('addChannel.enterValidUrl') }}
                    </div>
                    <div v-else class="d-flex flex-column ga-2 mt-1">
                      <div v-for="url in detectedBaseUrls" :key="url" class="base-url-item">
                        <div class="text-caption text-success">{{ url }}</div>
                        <div class="text-caption text-medium-emphasis">
                          {{ t('addChannel.expectedRequest') }} {{ getExpectedRequestUrl(url) }}
                        </div>
                      </div>
                    </div>
                  </div>
                  <v-chip v-if="detectedBaseUrls.length > 0" size="x-small" color="success" variant="tonal">
                    {{ t('addChannel.count', { count: detectedBaseUrls.length }) }}
                  </v-chip>
                </div>

                <v-row dense>
                  <v-col cols="12" md="7">
                    <div class="d-flex flex-column ga-3">
                      <div class="d-flex align-center ga-3 pa-3 bg-grey-lighten-4 rounded-lg">
                        <v-icon color="primary" size="20">mdi-tag</v-icon>
                        <div class="flex-grow-1">
                          <div class="text-caption text-medium-emphasis">{{ t('addChannel.channelName') }}</div>
                          <div class="text-body-2 font-weight-bold text-primary">
                            {{ generatedChannelName }}
                          </div>
                        </div>
                        <v-chip size="x-small" color="primary" variant="tonal">
                          {{ t('common.autoGenerated') }}
                        </v-chip>
                      </div>

                      <div class="d-flex align-center ga-3 pa-3 rounded-lg upstream-type-card" :style="upstreamTypeCardStyle">
                        <v-icon :color="quickServiceTypeColor" size="20">{{ quickServiceTypeIcon }}</v-icon>
                        <div class="text-caption text-medium-emphasis flex-shrink-0">
                          {{ t('channelEditor.basic.serviceType.label') }}
                        </div>
                        <v-spacer />
                        <v-select
                          v-model="quickServiceType"
                          :items="headerServiceTypeItems"
                          item-title="title"
                          item-value="value"
                          variant="plain"
                          density="compact"
                          hide-details
                          :base-color="quickServiceTypeColor"
                          :color="quickServiceTypeColor"
                          :menu-props="{ contentClass: 'upstream-select-menu' }"
                          class="upstream-select mt-n1"
                          @update:model-value="quickServiceTypeTouched = true"
                          @update:menu="onMenuUpdate"
                        />
                      </div>
                    </div>
                  </v-col>

                  <v-col cols="12" md="5">
                    <div class="d-flex flex-column ga-3">
                      <div class="d-flex align-center ga-3 pa-3 rounded-lg apikeys-card">
                        <v-icon :color="detectedApiKeys.length > 0 ? 'success' : 'error'" size="20">
                          {{ detectedApiKeys.length > 0 ? 'mdi-check-circle' : 'mdi-alert-circle' }}
                        </v-icon>
                        <div class="flex-grow-1">
                          <div class="text-body-2 font-weight-medium">{{ t('addChannel.apiKeys') }}</div>
                          <div class="text-caption" :class="detectedApiKeys.length > 0 ? 'text-success' : 'text-error'">
                            {{
                              detectedApiKeys.length > 0
                                ? t('addChannel.detectedKeys', { count: detectedApiKeys.length })
                                : t('addChannel.enterApiKey')
                            }}
                          </div>
                        </div>
                        <v-chip v-if="detectedApiKeys.length > 0" size="x-small" color="success" variant="tonal">
                          {{ t('addChannel.count', { count: detectedApiKeys.length }) }}
                        </v-chip>
                      </div>

                      <div
                        class="d-flex align-center ga-3 pa-3 rounded-lg cursor-pointer placement-switch-card"
                        @click="togglePlacement"
                      >
                        <v-icon color="primary" size="20">mdi-arrow-collapse-down</v-icon>
                        <div class="flex-grow-1">
                          <div class="text-body-2 font-weight-medium">{{ t('addChannel.newChannelPlacementLabel') }}</div>
                        </div>
                        <v-switch
                          :model-value="preferencesStore.newChannelPlacement === 'bottom'"
                          density="compact"
                          hide-details
                          readonly
                          color="primary"
                          inset
                          class="placement-switch ma-0 pa-0"
                          tabindex="-1"
                        />
                      </div>
                    </div>
                  </v-col>
                </v-row>
              </div>
            </v-card-text>
          </v-card>
        </div>
      </v-card-text>

      <v-card-actions class="pa-6 pt-0">
        <v-spacer />
        <v-btn variant="outlined" @click="handleCancel">
          {{ t('app.actions.cancel') }}
          <span class="shortcut-hint ml-2 text-xs opacity-50">Esc</span>
        </v-btn>
        <v-btn
          color="primary"
          variant="elevated"
          :disabled="!isQuickFormValid"
          prepend-icon="mdi-check"
          @click="handleQuickSubmit"
        >
          {{ t('addChannel.createChannel') }}
          <span class="shortcut-hint ml-2 text-xs opacity-50">{{ isMac ? '⌘Enter' : 'Ctrl+Enter' }}</span>
        </v-btn>
      </v-card-actions>
    </v-card>
  </v-dialog>
</template>

<script setup lang="ts">
import { computed, onMounted, onUnmounted, ref, watch } from 'vue'
import { useTheme } from 'vuetify'
import type { Channel } from '../services/api'
import { buildExpectedRequestUrls } from '../utils/expectedRequestUrls'
import { extractChannelNamePrefix } from '../utils/add-channel-modal-state'
import { parseQuickInput as parseQuickInputUtil } from '../utils/quickInputParser'
import { useI18n } from '../i18n'
import { usePreferencesStore } from '../stores/preferences'

type ServiceType = 'openai' | 'gemini' | 'claude' | 'responses' | 'copilot'
type ChannelType = 'messages' | 'chat' | 'responses' | 'gemini' | 'images'

interface Props {
  show: boolean
  channelType?: ChannelType
}

const props = withDefaults(defineProps<Props>(), {
  channelType: 'messages',
})

const emit = defineEmits<{
  'update:show': [value: boolean]
  save: [channel: Omit<Channel, 'index' | 'latency' | 'status'>, options?: { isQuickAdd?: boolean; triggerCapabilityTest?: boolean }]
  error: [message: string]
}>()

const { t } = useI18n()
const theme = useTheme()
const preferencesStore = usePreferencesStore()

const quickInput = ref('')
const detectedBaseUrl = ref('')
const detectedBaseUrls = ref<string[]>([])
const detectedApiKeys = ref<string[]>([])
const detectedServiceType = ref<ServiceType | null>(null)
const quickServiceTypeTouched = ref(false)
const quickServiceType = ref<ServiceType>(getDefaultServiceTypeValue())
const randomSuffix = ref(generateRandomString(6))

const isMac = computed(() => typeof navigator !== 'undefined' && /Mac|iPod|iPhone|iPad/.test(navigator.platform))

const headerClasses = computed(() => {
  const isDark = theme.global.current.value.dark
  return isDark ? 'bg-surface text-high-emphasis' : 'bg-primary text-white'
})

const avatarColor = computed(() => 'primary')

const headerIconStyle = computed(() => ({
  color: 'rgb(var(--v-theme-on-primary))',
}))

const subtitleClasses = computed(() => {
  const isDark = theme.global.current.value.dark
  return isDark ? 'text-medium-emphasis' : 'text-white-subtitle'
})

const serviceTypeOptions = computed(() => {
  const allOptions = [
    { title: 'OpenAI Chat', value: 'openai' as const },
    { title: 'Claude', value: 'claude' as const },
    { title: 'Gemini', value: 'gemini' as const },
    { title: 'Responses (Codex)', value: 'responses' as const },
    { title: 'GitHub Copilot', value: 'copilot' as const },
  ]

  const reorder = (options: typeof allOptions, first: ServiceType) => {
    const firstOption = options.find(option => option.value === first)
    const rest = options.filter(option => option.value !== first)
    return firstOption ? [firstOption, ...rest] : options
  }

  switch (props.channelType) {
    case 'messages':
      return reorder(allOptions, 'claude')
    case 'chat':
      return reorder(allOptions, 'openai')
    case 'responses':
      return reorder(allOptions, 'responses')
    case 'gemini':
      return reorder(allOptions, 'gemini')
    case 'images':
      return [{ title: 'OpenAI Images', value: 'openai' as const }]
    default:
      return allOptions
  }
})

const recommendedServiceType = computed<ServiceType | null>(() => {
  if (quickServiceTypeTouched.value) return null
  return detectedServiceType.value || getDefaultServiceTypeValue()
})

const headerServiceTypeItems = computed(() => {
  const suffix = t('addChannel.serviceTypeRecommendedSuffix')
  return serviceTypeOptions.value.map(option =>
    option.value === recommendedServiceType.value
      ? { ...option, title: `${option.title}${suffix}` }
      : option
  )
})

const quickServiceTypeIcon = computed(() => {
  const iconMap: Record<ServiceType, string> = {
    openai: 'mdi-robot',
    claude: 'mdi-message-processing',
    gemini: 'mdi-diamond-stone',
    responses: 'mdi-rocket-launch',
    copilot: 'mdi-code-braces',
  }
  return iconMap[quickServiceType.value] || 'mdi-api'
})

const quickServiceTypeColor = computed(() => {
  const colorMap: Record<ServiceType, string> = {
    openai: 'info',
    claude: 'orange',
    gemini: 'purple',
    responses: 'success',
    copilot: 'grey-darken-2',
  }
  return colorMap[quickServiceType.value] || 'primary'
})

const upstreamTypeCardStyle = computed(() => {
  const rgbMap: Record<ServiceType, string> = {
    openai: '59, 130, 246',
    claude: '249, 115, 22',
    gemini: '168, 85, 247',
    responses: '34, 197, 94',
    copilot: '36, 41, 47',
  }
  const rgb = rgbMap[quickServiceType.value] || '99, 102, 241'
  return {
    background: `rgba(${rgb}, 0.1)`,
  }
})

const generatedChannelName = computed(() => {
  if (!detectedBaseUrl.value) {
    return `channel-${randomSuffix.value}`
  }
  const prefix = extractChannelNamePrefix(detectedBaseUrl.value)
  return `${prefix}-${randomSuffix.value}`
})

const isQuickFormValid = computed(() => {
  return detectedBaseUrls.value.length > 0 && detectedApiKeys.value.length > 0
})

function getDefaultServiceTypeValue(): ServiceType {
  if (props.channelType === 'chat') return 'openai'
  if (props.channelType === 'gemini') return 'gemini'
  if (props.channelType === 'responses') return 'responses'
  if (props.channelType === 'images') return 'openai'
  return 'claude'
}

function generateRandomString(length: number): string {
  const chars = 'abcdefghijklmnopqrstuvwxyz0123456789'
  let result = ''
  for (let i = 0; i < length; i++) {
    result += chars.charAt(Math.floor(Math.random() * chars.length))
  }
  return result
}

function parseQuickInput() {
  const fallbackServiceType = props.channelType === 'images'
    ? 'openai'
    : quickServiceType.value
  const result = parseQuickInputUtil(quickInput.value, fallbackServiceType)
  detectedBaseUrl.value = result.detectedBaseUrl
  detectedBaseUrls.value = result.detectedBaseUrls
  detectedApiKeys.value = result.detectedApiKeys
  detectedServiceType.value = props.channelType === 'images'
    ? 'openai'
    : result.detectedServiceType

  if (!quickServiceTypeTouched.value && detectedServiceType.value) {
    quickServiceType.value = detectedServiceType.value
  }
}

function getExpectedRequestUrl(inputBaseUrl: string): string {
  if (!inputBaseUrl) return ''
  const serviceType = props.channelType === 'images' ? 'openai' : quickServiceType.value
  return buildExpectedRequestUrls(props.channelType, serviceType, inputBaseUrl)[0]?.expectedUrl || ''
}

function resetQuickState() {
  quickInput.value = ''
  detectedBaseUrl.value = ''
  detectedBaseUrls.value = []
  detectedApiKeys.value = []
  detectedServiceType.value = null
  quickServiceType.value = getDefaultServiceTypeValue()
  quickServiceTypeTouched.value = false
  randomSuffix.value = generateRandomString(6)
}

function togglePlacement() {
  preferencesStore.setNewChannelPlacement(
    preferencesStore.newChannelPlacement === 'bottom' ? 'top' : 'bottom',
  )
}

function handleQuickSubmit() {
  parseQuickInput()
  if (!isQuickFormValid.value) return

  emit('save', {
    name: generatedChannelName.value,
    serviceType: props.channelType === 'images' ? 'openai' : quickServiceType.value,
    baseUrl: detectedBaseUrl.value,
    baseUrls: detectedBaseUrls.value,
    apiKeys: detectedApiKeys.value,
    modelMapping: {},
  }, { isQuickAdd: true })
}

function handleCancel() {
  emit('update:show', false)
  resetQuickState()
}

function onMenuUpdate(open: boolean) {
  if (open) {
    setTimeout(() => window.dispatchEvent(new Event('resize')), 50)
  }
}

function handleKeydown(event: KeyboardEvent) {
  if (!props.show) return

  if (event.key === 'Escape') {
    event.preventDefault()
    handleCancel()
    return
  }

  if (event.key === 'Enter' && (event.metaKey || event.ctrlKey) && !event.shiftKey) {
    event.preventDefault()
    handleQuickSubmit()
  }
}

watch(
  () => props.show,
  show => {
    if (show) {
      resetQuickState()
    }
  },
  { immediate: true }
)

onMounted(() => {
  document.addEventListener('keydown', handleKeydown)
})

onUnmounted(() => {
  document.removeEventListener('keydown', handleKeydown)
})
</script>

<style scoped>
.add-channel-dialog {
  overflow: hidden;
}

.modal-header-text {
  min-width: 0;
}

.modal-title {
  font-size: 1.125rem;
  font-weight: 700;
  line-height: 1.2;
}

.modal-subtitle {
  margin-top: 2px;
  font-size: 0.875rem;
  line-height: 1.35;
}

.text-white-subtitle {
  color: rgba(255, 255, 255, 0.86);
}

.quick-input-textarea {
  width: 100%;
}

.detection-status-card {
  border-color: rgba(var(--v-theme-outline), 0.32);
}

.base-url-item {
  padding: 2px 0;
}

.upstream-type-card {
  border: 1px solid rgba(var(--v-theme-outline), 0.32);
}

.upstream-select {
  min-width: 160px;
}

.apikeys-card {
  border: 1px solid rgba(var(--v-theme-outline), 0.32);
}
.placement-switch-card {
  border: 1px solid rgba(var(--v-theme-outline), 0.32);
  transition: border-color 0.15s ease, background 0.15s ease;
}
.placement-switch-card:hover {
  border-color: rgba(var(--v-theme-primary), 0.45);
  background: rgba(var(--v-theme-primary), 0.04);
}
.placement-switch {
  flex-shrink: 0;
  pointer-events: none;
}
.placement-switch :deep(.v-selection-control) {
  min-height: auto;
}

.shortcut-hint {
  font-size: 0.75rem;
  opacity: 0.55;
}

.key-tooltip {
  max-width: 320px;
}
</style>
