<template>
  <v-dialog :model-value="show" max-width="800" persistent @update:model-value="$emit('update:show', $event)">
    <v-card rounded="lg" class="add-channel-dialog">
      <v-card-title class="d-flex align-center ga-3 pa-6" :class="headerClasses">
        <v-avatar :color="avatarColor" variant="flat" size="40">
          <v-icon :style="headerIconStyle" size="20">mdi-plus</v-icon>
        </v-avatar>
        <div class="flex-grow-1 modal-header-text">
          <div class="modal-title">
            {{ t('addChannel.createTitle') }}
          </div>
          <div class="modal-subtitle" :class="subtitleClasses">
            {{ t('addChannel.quickSubtitle') }}
          </div>
        </div>
      </v-card-title>

      <v-card-text class="pa-6">
        <!-- 模式切换 -->
        <div class="d-flex justify-center mb-4">
          <v-btn-toggle
            v-model="quickAddMode"
            mandatory
            density="compact"
            rounded="lg"
            color="primary"
            variant="outlined"
          >
            <v-btn :value="false" size="small">
              <v-icon start size="small">mdi-text</v-icon>
              {{ t('autopilot.quickAdd.modeStandard') }}
            </v-btn>
            <v-btn :value="true" size="small">
              <v-icon start size="small">mdi-auto-fix</v-icon>
              {{ t('autopilot.quickAdd.modeQuick') }}
            </v-btn>
          </v-btn-toggle>
        </div>

        <!-- 快速添加模式 -->
        <QuickAddChannelForm
          v-if="quickAddMode"
          ref="quickAddFormRef"
          :channel-type="channelType"
          @added="onQuickAddSuccess"
        />

        <!-- 标准模式（现有 textarea 解析） -->
        <div v-else class="d-flex flex-column ga-3">
          <v-textarea
            v-model="quickInput"
            :label="t('addChannel.quickInputLabel')"
            :placeholder="t('addChannel.quickInputPlaceholder')"
            variant="outlined"
            rows="10"
            no-resize
            autofocus
            class="quick-input-textarea"
            @input="parseQuickInput"
          />

          <v-card variant="outlined" class="detection-status-card" rounded="lg">
            <v-card-text class="pa-4">
              <div class="d-flex flex-column ga-3">
                <div class="d-flex align-start ga-3">
                  <v-icon :color="detectedBaseUrls.length > 0 ? 'success' : 'error'" size="20" class="mt-1">
                    {{ detectedBaseUrls.length > 0 ? 'mdi-check-circle' : 'mdi-alert-circle' }}
                  </v-icon>
                  <div class="flex-grow-1">
                    <div class="text-body-2 font-weight-medium">{{ t('addChannel.baseUrl') }}</div>
                    <div v-if="detectedBaseUrls.length === 0" class="text-caption text-error">
                      {{ t('addChannel.enterValidUrl') }}
                    </div>
                    <div v-else class="d-flex flex-column ga-2 mt-1">
                      <div v-for="url in detectedBaseUrls" :key="url" class="base-url-item">
                        <div class="text-caption text-success">{{ url }}</div>
                        <div class="text-caption text-medium-emphasis">
                          {{ t('addChannel.expectedRequest') }} {{ getExpectedRequestUrl(url) }}
                        </div>
                      </div>
                    </div>
                  </div>
                  <v-chip v-if="detectedBaseUrls.length > 0" size="x-small" color="success" variant="tonal">
                    {{ t('addChannel.count', { count: detectedBaseUrls.length }) }}
                  </v-chip>
                </div>

                <v-row dense>
                  <v-col cols="12" md="7">
                    <div class="d-flex flex-column ga-3">
                      <div class="d-flex align-center ga-3 pa-3 bg-grey-lighten-4 rounded-lg">
                        <v-icon color="primary" size="20">mdi-tag</v-icon>
                        <div class="flex-grow-1">
                          <div class="text-caption text-medium-emphasis">{{ t('addChannel.channelName') }}</div>
                          <div class="text-body-2 font-weight-bold text-primary">
                            {{ generatedChannelName }}
                          </div>
                        </div>
                        <v-chip size="x-small" color="primary" variant="tonal">
                          {{ t('common.autoGenerated') }}
                        </v-chip>
                      </div>
                    </div>
                  </v-col>

                  <v-col cols="12" md="5">
                    <div class="d-flex flex-column ga-3">
                      <div class="d-flex align-center ga-3 pa-3 rounded-lg apikeys-card">
                        <v-icon :color="apiKeyStatusColor" size="20">
                          {{ apiKeyStatusIcon }}
                        </v-icon>
                        <div class="flex-grow-1">
                          <div class="text-body-2 font-weight-medium">{{ t('addChannel.apiKeys') }}</div>
                          <div class="text-caption" :class="apiKeyStatusTextClass">
                            {{ apiKeyStatusMessage }}
                          </div>
                        </div>
                        <v-chip v-if="detectedApiKeys.length > 0" size="x-small" color="success" variant="tonal">
                          {{ t('addChannel.count', { count: detectedApiKeys.length }) }}
                        </v-chip>
                      </div>

                      <div
                        class="d-flex align-center ga-3 pa-3 rounded-lg cursor-pointer placement-switch-card"
                        @click="togglePlacement"
                      >
                        <v-icon color="primary" size="20">mdi-arrow-collapse-down</v-icon>
                        <div class="flex-grow-1">
                          <div class="text-body-2 font-weight-medium">
                            {{ t('addChannel.newChannelPlacementLabel') }}
                          </div>
                        </div>
                        <v-switch
                          :model-value="getNewChannelPlacement() === 'bottom'"
                          density="compact"
                          hide-details
                          readonly
                          color="primary"
                          inset
                          class="placement-switch ma-0 pa-0"
                          tabindex="-1"
                        />
                      </div>
                    </div>
                  </v-col>
                </v-row>

                <v-alert
                  v-if="quickServiceType === 'copilot'"
                  class="mt-3"
                  color="info"
                  variant="tonal"
                  density="comfortable"
                >
                  {{ t('copilotOAuth.quickAddHint') }}
                </v-alert>
              </div>
            </v-card-text>
          </v-card>
        </div>
      </v-card-text>

      <v-card-actions class="pa-6 pt-0">
        <v-spacer />
        <v-btn variant="outlined" @click="handleCancel">
          {{ t('app.actions.cancel') }}
          <span class="shortcut-hint ml-2 text-xs opacity-50">Esc</span>
        </v-btn>
        <v-btn
          color="primary"
          variant="elevated"
          :disabled="quickAddMode ? !quickAddFormRef?.isFormValid : !isQuickFormValid"
          :loading="quickAddMode ? quickAddFormRef?.submitting : false"
          prepend-icon="mdi-check"
          @click="handleSubmitByMode"
        >
          {{ t('addChannel.createChannel') }}
          <span class="shortcut-hint ml-2 text-xs opacity-50">{{ isMac ? '⌘Enter' : 'Ctrl+Enter' }}</span>
        </v-btn>
      </v-card-actions>
    </v-card>
  </v-dialog>
</template>

<script setup lang="ts">
import { computed, onMounted, onUnmounted, ref, unref, watch } from 'vue'
import { useTheme } from 'vuetify'
import type { Channel } from '../services/api'
import { buildExpectedRequestUrls } from '../utils/expectedRequestUrls'
import { extractChannelNamePrefix } from '../utils/add-channel-modal-state'
import { parseQuickInput as parseQuickInputUtil } from '../utils/quickInputParser'
import { useI18n } from '../i18n'
import { useAuthStore } from '../stores/auth'
import { usePreferencesStore } from '../stores/preferences'
import { preloadProviderTemplates } from '../services/autopilot-api'
import QuickAddChannelForm from './QuickAddChannelForm.vue'

type ServiceType = 'openai' | 'gemini' | 'claude' | 'responses' | 'copilot'
type ChannelType = 'messages' | 'chat' | 'responses' | 'gemini' | 'images' | 'vectors'

interface Props {
  show: boolean
  channelType?: ChannelType
}

const props = withDefaults(defineProps<Props>(), {
  channelType: 'messages'
})

const emit = defineEmits<{
  'update:show': [value: boolean]
  save: [
    channel: Omit<Channel, 'index' | 'latency' | 'status'>,
    options?: { isQuickAdd?: boolean; triggerCapabilityTest?: boolean }
  ]
  error: [message: string]
  autoAdded: [channelId: number]
}>()

const { t } = useI18n()
const theme = useTheme()
const authStore = useAuthStore()
const preferencesStore = usePreferencesStore()
const getNewChannelPlacement = () => unref(preferencesStore.newChannelPlacement)

const quickInput = ref('')
const detectedBaseUrl = ref('')
const detectedBaseUrls = ref<string[]>([])
const detectedApiKeys = ref<string[]>([])
// 标准模式仅自动识别类型；无法识别时按当前渠道页签使用默认类型。
const quickServiceType = ref<ServiceType>(getDefaultServiceTypeValue())
const randomSuffix = ref(generateRandomString(6))

// 快速添加模式
const quickAddMode = ref(false)
const quickAddFormRef = ref<InstanceType<typeof QuickAddChannelForm> | null>(null)

const isMac = computed(() => typeof navigator !== 'undefined' && /Mac|iPod|iPhone|iPad/.test(navigator.platform))

const headerClasses = computed(() => {
  const isDark = theme.global.current.value.dark
  return isDark ? 'bg-surface text-high-emphasis' : 'bg-primary text-white'
})

const avatarColor = computed(() => 'primary')

const headerIconStyle = computed(() => ({
  color: 'rgb(var(--v-theme-on-primary))'
}))

const subtitleClasses = computed(() => {
  const isDark = theme.global.current.value.dark
  return isDark ? 'text-medium-emphasis' : 'text-white-subtitle'
})

const isCopilotQuickAdd = computed(() => quickServiceType.value === 'copilot')

const apiKeyStatusColor = computed(() => {
  if (detectedApiKeys.value.length > 0) return 'success'
  return isCopilotQuickAdd.value ? 'info' : 'error'
})

const apiKeyStatusIcon = computed(() => {
  if (detectedApiKeys.value.length > 0) return 'mdi-check-circle'
  return isCopilotQuickAdd.value ? 'mdi-information' : 'mdi-alert-circle'
})

const apiKeyStatusTextClass = computed(() => {
  if (detectedApiKeys.value.length > 0) return 'text-success'
  return isCopilotQuickAdd.value ? 'text-info' : 'text-error'
})

const apiKeyStatusMessage = computed(() => {
  if (detectedApiKeys.value.length > 0) {
    return t('addChannel.detectedKeys', { count: detectedApiKeys.value.length })
  }
  return isCopilotQuickAdd.value ? t('copilotOAuth.quickAddKeyHint') : t('addChannel.enterApiKey')
})

const generatedChannelName = computed(() => {
  if (!detectedBaseUrl.value) {
    return `channel-${randomSuffix.value}`
  }
  const prefix = extractChannelNamePrefix(detectedBaseUrl.value)
  return `${prefix}-${randomSuffix.value}`
})

const isQuickFormValid = computed(() => {
  if (isCopilotQuickAdd.value) {
    return detectedBaseUrls.value.length > 0
  }
  return detectedBaseUrls.value.length > 0 && detectedApiKeys.value.length > 0
})

function getDefaultServiceTypeValue(): ServiceType {
  if (props.channelType === 'chat') return 'openai'
  if (props.channelType === 'gemini') return 'gemini'
  if (props.channelType === 'responses') return 'responses'
  if (props.channelType === 'images' || props.channelType === 'vectors') return 'openai'
  return 'claude'
}

function generateRandomString(length: number): string {
  const chars = 'abcdefghijklmnopqrstuvwxyz0123456789'
  let result = ''
  for (let i = 0; i < length; i++) {
    result += chars.charAt(Math.floor(Math.random() * chars.length))
  }
  return result
}

function parseQuickInput() {
  const fallbackServiceType = getDefaultServiceTypeValue()
  const result = parseQuickInputUtil(quickInput.value, fallbackServiceType)
  detectedBaseUrl.value = result.detectedBaseUrl
  detectedBaseUrls.value = result.detectedBaseUrls
  detectedApiKeys.value = result.detectedApiKeys
  const detectedServiceType =
    props.channelType === 'images' || props.channelType === 'vectors' ? 'openai' : result.detectedServiceType
  quickServiceType.value = detectedServiceType || fallbackServiceType
}

function getExpectedRequestUrl(inputBaseUrl: string): string {
  if (!inputBaseUrl) return ''
  const serviceType =
    props.channelType === 'images' || props.channelType === 'vectors' ? 'openai' : quickServiceType.value
  return buildExpectedRequestUrls(props.channelType, serviceType, inputBaseUrl)[0]?.expectedUrl || ''
}

function resetQuickState() {
  quickInput.value = ''
  detectedBaseUrl.value = ''
  detectedBaseUrls.value = []
  detectedApiKeys.value = []
  quickServiceType.value = getDefaultServiceTypeValue()
  randomSuffix.value = generateRandomString(6)
}

function togglePlacement() {
  preferencesStore.setNewChannelPlacement(getNewChannelPlacement() === 'bottom' ? 'top' : 'bottom')
}

function handleQuickSubmit() {
  parseQuickInput()
  if (!isQuickFormValid.value) return

  const channel = {
    name: generatedChannelName.value,
    serviceType: props.channelType === 'images' || props.channelType === 'vectors' ? 'openai' : quickServiceType.value,
    baseUrl: detectedBaseUrl.value,
    baseUrls: detectedBaseUrls.value,
    apiKeys: detectedApiKeys.value,
    modelMapping: {}
  }

  if (props.channelType !== 'messages') {
    Object.assign(channel, { normalizeMetadataUserId: false })
  }

  emit('save', channel, { isQuickAdd: true })
}

function handleSubmitByMode() {
  if (quickAddMode.value) {
    quickAddFormRef.value?.handleSubmit()
  } else {
    handleQuickSubmit()
  }
}

function onQuickAddSuccess(channelId: number) {
  emit('autoAdded', channelId)
  quickAddFormRef.value?.resetForm()
  resetQuickState()
  quickAddMode.value = false
}

function handleCancel() {
  emit('update:show', false)
  resetQuickState()
  quickAddMode.value = false
  quickAddFormRef.value?.resetForm()
}

function handleKeydown(event: KeyboardEvent) {
  if (!props.show) return

  if (event.key === 'Escape') {
    event.preventDefault()
    handleCancel()
    return
  }

  if (event.key === 'Enter' && (event.metaKey || event.ctrlKey) && !event.shiftKey) {
    event.preventDefault()
    handleSubmitByMode()
  }
}

watch(
  () => props.show,
  show => {
    if (show) {
      if (authStore.isAuthenticated) void preloadProviderTemplates()
      resetQuickState()
    }
  },
  { immediate: true }
)

watch(
  () => authStore.apiKey,
  apiKey => {
    if (apiKey) void preloadProviderTemplates()
  },
  { immediate: true }
)

onMounted(() => {
  document.addEventListener('keydown', handleKeydown)
})

onUnmounted(() => {
  document.removeEventListener('keydown', handleKeydown)
})
</script>

<style scoped>
.add-channel-dialog {
  overflow: hidden;
}

.modal-header-text {
  min-width: 0;
}

.modal-title {
  font-size: 1.125rem;
  font-weight: 700;
  line-height: 1.2;
}

.modal-subtitle {
  margin-top: 2px;
  font-size: 0.875rem;
  line-height: 1.35;
}

.text-white-subtitle {
  color: rgba(255, 255, 255, 0.86);
}

.quick-input-textarea {
  width: 100%;
}

.detection-status-card {
  border-color: rgba(var(--v-theme-outline), 0.32);
}

.base-url-item {
  padding: 2px 0;
}

.apikeys-card {
  border: 1px solid rgba(var(--v-theme-outline), 0.32);
}
.placement-switch-card {
  border: 1px solid rgba(var(--v-theme-outline), 0.32);
  transition:
    border-color 0.15s ease,
    background 0.15s ease;
}
.placement-switch-card:hover {
  border-color: rgba(var(--v-theme-primary), 0.45);
  background: rgba(var(--v-theme-primary), 0.04);
}
.placement-switch {
  flex-shrink: 0;
  pointer-events: none;
}
.placement-switch :deep(.v-selection-control) {
  min-height: auto;
}

.shortcut-hint {
  font-size: 0.75rem;
  opacity: 0.55;
}

.key-tooltip {
  max-width: 320px;
}
</style>
