// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class AgentConfigStatus {
    /**
     * Creates a new AgentConfigStatus instance.
     * @param {Partial<AgentConfigStatus>} [$$source = {}] - The source object to create the AgentConfigStatus.
     */
    constructor($$source = {}) {
        if (!("platform" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["platform"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["provider"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["targetProvider"] = undefined;
        }
        if (!("configured" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["configured"] = false;
        }
        if (!("matchesCurrentPort" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["matchesCurrentPort"] = false;
        }
        if (!("needsUpdate" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["needsUpdate"] = false;
        }
        if (!("currentBaseUrl" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["currentBaseUrl"] = "";
        }
        if (!("targetBaseUrl" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["targetBaseUrl"] = "";
        }
        if (!("configPath" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["configPath"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["authPath"] = undefined;
        }
        if (!("hasState" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["hasState"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["lastError"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AgentConfigStatus instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {AgentConfigStatus}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AgentConfigStatus(/** @type {Partial<AgentConfigStatus>} */($$parsedSource));
    }
}

export class ApplyAgentConfigRequest {
    /**
     * Creates a new ApplyAgentConfigRequest instance.
     * @param {Partial<ApplyAgentConfigRequest>} [$$source = {}] - The source object to create the ApplyAgentConfigRequest.
     */
    constructor($$source = {}) {
        if (!("platform" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["platform"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["provider"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["apiKey"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["baseUrl"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ApplyAgentConfigRequest instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ApplyAgentConfigRequest}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ApplyAgentConfigRequest(/** @type {Partial<ApplyAgentConfigRequest>} */($$parsedSource));
    }
}

export class ConfigDiffResult {
    /**
     * Creates a new ConfigDiffResult instance.
     * @param {Partial<ConfigDiffResult>} [$$source = {}] - The source object to create the ConfigDiffResult.
     */
    constructor($$source = {}) {
        if (!("files" in $$source)) {
            /**
             * @member
             * @type {FileDiff[]}
             */
            this["files"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ConfigDiffResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ConfigDiffResult}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("files" in $$parsedSource) {
            $$parsedSource["files"] = $$createField0_0($$parsedSource["files"]);
        }
        return new ConfigDiffResult(/** @type {Partial<ConfigDiffResult>} */($$parsedSource));
    }
}

export class DiffLine {
    /**
     * Creates a new DiffLine instance.
     * @param {Partial<DiffLine>} [$$source = {}] - The source object to create the DiffLine.
     */
    constructor($$source = {}) {
        if (!("type" in $$source)) {
            /**
             * "context" | "added" | "removed"
             * @member
             * @type {string}
             */
            this["type"] = "";
        }
        if (!("content" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["content"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DiffLine instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {DiffLine}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DiffLine(/** @type {Partial<DiffLine>} */($$parsedSource));
    }
}

export class FileDiff {
    /**
     * Creates a new FileDiff instance.
     * @param {Partial<FileDiff>} [$$source = {}] - The source object to create the FileDiff.
     */
    constructor($$source = {}) {
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (!("action" in $$source)) {
            /**
             * "modify" | "create" | "delete"
             * @member
             * @type {string}
             */
            this["action"] = "";
        }
        if (!("lines" in $$source)) {
            /**
             * @member
             * @type {DiffLine[]}
             */
            this["lines"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FileDiff instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {FileDiff}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("lines" in $$parsedSource) {
            $$parsedSource["lines"] = $$createField2_0($$parsedSource["lines"]);
        }
        return new FileDiff(/** @type {Partial<FileDiff>} */($$parsedSource));
    }
}

export class ProviderKeyAsset {
    /**
     * Creates a new ProviderKeyAsset instance.
     * @param {Partial<ProviderKeyAsset>} [$$source = {}] - The source object to create the ProviderKeyAsset.
     */
    constructor($$source = {}) {
        if (!("provider" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["provider"] = "";
        }
        if (!("apiKey" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["apiKey"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["baseUrl"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["planId"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string[] | undefined}
             */
            this["usages"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProviderKeyAsset instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ProviderKeyAsset}
     */
    static createFrom($$source = {}) {
        const $$createField4_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("usages" in $$parsedSource) {
            $$parsedSource["usages"] = $$createField4_0($$parsedSource["usages"]);
        }
        return new ProviderKeyAsset(/** @type {Partial<ProviderKeyAsset>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = FileDiff.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = DiffLine.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = $Create.Array($Create.Any);
