// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class ChannelTarget {
    /**
     * Creates a new ChannelTarget instance.
     * @param {Partial<ChannelTarget>} [$$source = {}] - The source object to create the ChannelTarget.
     */
    constructor($$source = {}) {
        if (!("type" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["type"] = "";
        }
        if (!("label" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["label"] = "";
        }
        if (!("description" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["description"] = "";
        }
        if (!("recommended" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["recommended"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ChannelTarget instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ChannelTarget}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ChannelTarget(/** @type {Partial<ChannelTarget>} */($$parsedSource));
    }
}

export class CreateChannelRequest {
    /**
     * Creates a new CreateChannelRequest instance.
     * @param {Partial<CreateChannelRequest>} [$$source = {}] - The source object to create the CreateChannelRequest.
     */
    constructor($$source = {}) {
        if (!("provider" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["provider"] = "";
        }
        if (!("target" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["target"] = "";
        }
        if (!("planId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["planId"] = "";
        }
        if (!("baseUrl" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["baseUrl"] = "";
        }
        if (!("apiKey" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["apiKey"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("description" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["description"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CreateChannelRequest instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {CreateChannelRequest}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CreateChannelRequest(/** @type {Partial<CreateChannelRequest>} */($$parsedSource));
    }
}

export class CreateChannelResult {
    /**
     * Creates a new CreateChannelResult instance.
     * @param {Partial<CreateChannelResult>} [$$source = {}] - The source object to create the CreateChannelResult.
     */
    constructor($$source = {}) {
        if (!("provider" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["provider"] = "";
        }
        if (!("target" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["target"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("baseUrl" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["baseUrl"] = "";
        }
        if (!("message" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["message"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CreateChannelResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {CreateChannelResult}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CreateChannelResult(/** @type {Partial<CreateChannelResult>} */($$parsedSource));
    }
}

export class ProviderPlan {
    /**
     * Creates a new ProviderPlan instance.
     * @param {Partial<ProviderPlan>} [$$source = {}] - The source object to create the ProviderPlan.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("label" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["label"] = "";
        }
        if (!("baseUrl" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["baseUrl"] = "";
        }
        if (!("description" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["description"] = "";
        }
        if (!("recommended" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["recommended"] = false;
        }
        if (!("custom" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["custom"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProviderPlan instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ProviderPlan}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ProviderPlan(/** @type {Partial<ProviderPlan>} */($$parsedSource));
    }
}

export class ProviderPreset {
    /**
     * Creates a new ProviderPreset instance.
     * @param {Partial<ProviderPreset>} [$$source = {}] - The source object to create the ProviderPreset.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("label" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["label"] = "";
        }
        if (!("description" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["description"] = "";
        }
        if (!("directAgent" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["directAgent"] = false;
        }
        if (!("nativeMessages" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["nativeMessages"] = false;
        }
        if (!("chatCompatible" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["chatCompatible"] = false;
        }
        if (!("responsesCompatible" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["responsesCompatible"] = false;
        }
        if (!("plans" in $$source)) {
            /**
             * @member
             * @type {ProviderPlan[]}
             */
            this["plans"] = [];
        }
        if (!("targets" in $$source)) {
            /**
             * @member
             * @type {ChannelTarget[]}
             */
            this["targets"] = [];
        }
        if (!("defaultTarget" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["defaultTarget"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProviderPreset instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ProviderPreset}
     */
    static createFrom($$source = {}) {
        const $$createField7_0 = $$createType1;
        const $$createField8_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("plans" in $$parsedSource) {
            $$parsedSource["plans"] = $$createField7_0($$parsedSource["plans"]);
        }
        if ("targets" in $$parsedSource) {
            $$parsedSource["targets"] = $$createField8_0($$parsedSource["targets"]);
        }
        return new ProviderPreset(/** @type {Partial<ProviderPreset>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = ProviderPlan.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = ChannelTarget.createFrom;
const $$createType3 = $Create.Array($$createType2);
