// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class ChannelTarget {
    "type": string;
    "label": string;
    "description": string;
    "recommended": boolean;

    /** Creates a new ChannelTarget instance. */
    constructor($$source: Partial<ChannelTarget> = {}) {
        if (!("type" in $$source)) {
            this["type"] = "";
        }
        if (!("label" in $$source)) {
            this["label"] = "";
        }
        if (!("description" in $$source)) {
            this["description"] = "";
        }
        if (!("recommended" in $$source)) {
            this["recommended"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ChannelTarget instance from a string or object.
     */
    static createFrom($$source: any = {}): ChannelTarget {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ChannelTarget($$parsedSource as Partial<ChannelTarget>);
    }
}

export class CreateChannelRequest {
    "provider": string;
    "target": string;
    "planId": string;
    "baseUrl": string;
    "apiKey": string;
    "name": string;
    "description": string;
    "proxyUrl": string;

    /** Creates a new CreateChannelRequest instance. */
    constructor($$source: Partial<CreateChannelRequest> = {}) {
        if (!("provider" in $$source)) {
            this["provider"] = "";
        }
        if (!("target" in $$source)) {
            this["target"] = "";
        }
        if (!("planId" in $$source)) {
            this["planId"] = "";
        }
        if (!("baseUrl" in $$source)) {
            this["baseUrl"] = "";
        }
        if (!("apiKey" in $$source)) {
            this["apiKey"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("description" in $$source)) {
            this["description"] = "";
        }
        if (!("proxyUrl" in $$source)) {
            this["proxyUrl"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CreateChannelRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): CreateChannelRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CreateChannelRequest($$parsedSource as Partial<CreateChannelRequest>);
    }
}

export class CreateChannelResult {
    "provider": string;
    "target": string;
    "name": string;
    "baseUrl": string;
    "message": string;

    /** Creates a new CreateChannelResult instance. */
    constructor($$source: Partial<CreateChannelResult> = {}) {
        if (!("provider" in $$source)) {
            this["provider"] = "";
        }
        if (!("target" in $$source)) {
            this["target"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("baseUrl" in $$source)) {
            this["baseUrl"] = "";
        }
        if (!("message" in $$source)) {
            this["message"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CreateChannelResult instance from a string or object.
     */
    static createFrom($$source: any = {}): CreateChannelResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CreateChannelResult($$parsedSource as Partial<CreateChannelResult>);
    }
}

export class ProviderPlan {
    "id": string;
    "label": string;
    "baseUrl": string;
    "description": string;
    "recommended": boolean;
    "custom": boolean;

    /** Creates a new ProviderPlan instance. */
    constructor($$source: Partial<ProviderPlan> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("label" in $$source)) {
            this["label"] = "";
        }
        if (!("baseUrl" in $$source)) {
            this["baseUrl"] = "";
        }
        if (!("description" in $$source)) {
            this["description"] = "";
        }
        if (!("recommended" in $$source)) {
            this["recommended"] = false;
        }
        if (!("custom" in $$source)) {
            this["custom"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProviderPlan instance from a string or object.
     */
    static createFrom($$source: any = {}): ProviderPlan {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ProviderPlan($$parsedSource as Partial<ProviderPlan>);
    }
}

export class ProviderPreset {
    "id": string;
    "order": number;
    "label": string;
    "description": string;
    "directAgent": boolean;
    "nativeMessages": boolean;
    "chatCompatible": boolean;
    "responsesCompatible": boolean;
    "plans": ProviderPlan[];
    "targets": ChannelTarget[];
    "defaultTarget": string;

    /** Creates a new ProviderPreset instance. */
    constructor($$source: Partial<ProviderPreset> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("order" in $$source)) {
            this["order"] = 0;
        }
        if (!("label" in $$source)) {
            this["label"] = "";
        }
        if (!("description" in $$source)) {
            this["description"] = "";
        }
        if (!("directAgent" in $$source)) {
            this["directAgent"] = false;
        }
        if (!("nativeMessages" in $$source)) {
            this["nativeMessages"] = false;
        }
        if (!("chatCompatible" in $$source)) {
            this["chatCompatible"] = false;
        }
        if (!("responsesCompatible" in $$source)) {
            this["responsesCompatible"] = false;
        }
        if (!("plans" in $$source)) {
            this["plans"] = [];
        }
        if (!("targets" in $$source)) {
            this["targets"] = [];
        }
        if (!("defaultTarget" in $$source)) {
            this["defaultTarget"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProviderPreset instance from a string or object.
     */
    static createFrom($$source: any = {}): ProviderPreset {
        const $$createField8_0 = $$createType1;
        const $$createField9_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("plans" in $$parsedSource) {
            $$parsedSource["plans"] = $$createField8_0($$parsedSource["plans"]);
        }
        if ("targets" in $$parsedSource) {
            $$parsedSource["targets"] = $$createField9_0($$parsedSource["targets"]);
        }
        return new ProviderPreset($$parsedSource as Partial<ProviderPreset>);
    }
}

// Private type creation functions
const $$createType0 = ProviderPlan.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = ChannelTarget.createFrom;
const $$createType3 = $Create.Array($$createType2);
