// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as backend$0 from "./internal/backend/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as channelpreset$0 from "./internal/channelpreset/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as configservice$0 from "./internal/configservice/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as editor$0 from "./internal/editor/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function ApplyAgentConfig(req: configservice$0.ApplyAgentConfigRequest): $CancellablePromise<void> {
    return $Call.ByID(1194974726, req);
}

/**
 * CopyText 把文本写入系统剪贴板。
 */
export function CopyText(text: string): $CancellablePromise<void> {
    return $Call.ByID(2418202931, text);
}

export function CreateCCXChannelFromPreset(req: channelpreset$0.CreateChannelRequest): $CancellablePromise<channelpreset$0.CreateChannelResult> {
    return $Call.ByID(3922694447, req).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * DetectEditors 返回系统上可用的文本编辑器列表。
 */
export function DetectEditors(): $CancellablePromise<editor$0.Editor[]> {
    return $Call.ByID(1308494416).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * GenerateProxyAccessKey 仅生成预览密钥，不写入任何文件。
 */
export function GenerateProxyAccessKey(): $CancellablePromise<string> {
    return $Call.ByID(1874658839);
}

export function GetAgentConfigStatus(platform: string): $CancellablePromise<configservice$0.AgentConfigStatus> {
    return $Call.ByID(3013260948, platform).then(($result: any) => {
        return $$createType3($result);
    });
}

export function GetAutostartStatus(): $CancellablePromise<boolean> {
    return $Call.ByID(1022089850);
}

export function GetEnvFile(): $CancellablePromise<$models.EnvFileState> {
    return $Call.ByID(4130444060).then(($result: any) => {
        return $$createType4($result);
    });
}

export function GetLogs(): $CancellablePromise<string[]> {
    return $Call.ByID(1688970508).then(($result: any) => {
        return $$createType5($result);
    });
}

export function GetProviderKeyAssets(): $CancellablePromise<configservice$0.ProviderKeyAsset[]> {
    return $Call.ByID(1999783760).then(($result: any) => {
        return $$createType7($result);
    });
}

export function GetProviderPresets(target: string): $CancellablePromise<channelpreset$0.ProviderPreset[]> {
    return $Call.ByID(764436626, target).then(($result: any) => {
        return $$createType9($result);
    });
}

export function GetProxyAccessKey(): $CancellablePromise<string> {
    return $Call.ByID(355938326);
}

export function GetSavedProviderKeys(): $CancellablePromise<{ [_ in string]?: string }> {
    return $Call.ByID(2703245855).then(($result: any) => {
        return $$createType10($result);
    });
}

export function GetStatus(): $CancellablePromise<backend$0.Status> {
    return $Call.ByID(2036427713).then(($result: any) => {
        return $$createType11($result);
    });
}

/**
 * GetVersion 返回构建时注入的版本信息。
 */
export function GetVersion(): $CancellablePromise<$models.VersionInfo> {
    return $Call.ByID(3507009081).then(($result: any) => {
        return $$createType12($result);
    });
}

/**
 * IsSetupComplete 判断是否已完成初始配置（PROXY_ACCESS_KEY 已存在）。
 */
export function IsSetupComplete(): $CancellablePromise<boolean> {
    return $Call.ByID(375603581);
}

/**
 * OpenDirectory 在系统文件管理器中打开目录。
 */
export function OpenDirectory(dirPath: string): $CancellablePromise<void> {
    return $Call.ByID(2081295652, dirPath);
}

/**
 * OpenEnvFileInEditor 使用指定编辑器打开 .env 文件。
 */
export function OpenEnvFileInEditor(editorPath: string): $CancellablePromise<void> {
    return $Call.ByID(2255035236, editorPath);
}

/**
 * OpenFileInEditor 使用指定编辑器打开任意文件。
 */
export function OpenFileInEditor(editorPath: string, filePath: string): $CancellablePromise<void> {
    return $Call.ByID(1960821709, editorPath, filePath);
}

export function OpenWebUIInBrowser(): $CancellablePromise<void> {
    return $Call.ByID(2011844568);
}

export function PreviewAgentConfigDiff(req: configservice$0.ApplyAgentConfigRequest): $CancellablePromise<configservice$0.ConfigDiffResult> {
    return $Call.ByID(2249637809, req).then(($result: any) => {
        return $$createType13($result);
    });
}

export function PreviewRestoreConfigDiff(platform: string): $CancellablePromise<configservice$0.ConfigDiffResult> {
    return $Call.ByID(2382293170, platform).then(($result: any) => {
        return $$createType13($result);
    });
}

export function RestartService(): $CancellablePromise<void> {
    return $Call.ByID(194936479);
}

export function RestoreAgentConfig(platform: string): $CancellablePromise<void> {
    return $Call.ByID(3544811620, platform);
}

export function SaveEnvFile(content: string): $CancellablePromise<void> {
    return $Call.ByID(4266218857, content);
}

export function SetAutostart(enabled: boolean): $CancellablePromise<void> {
    return $Call.ByID(3109129572, enabled);
}

export function ShowAgentTab(): $CancellablePromise<void> {
    return $Call.ByID(978526812);
}

export function ShowStatusTab(): $CancellablePromise<void> {
    return $Call.ByID(1026910485);
}

export function ShowWebUITab(): $CancellablePromise<void> {
    return $Call.ByID(1839858715);
}

export function Shutdown(): $CancellablePromise<void> {
    return $Call.ByID(3879395531);
}

export function StartService(): $CancellablePromise<void> {
    return $Call.ByID(220274594);
}

export function StopService(): $CancellablePromise<void> {
    return $Call.ByID(2326025444);
}

/**
 * WebURL 返回当前网关 Web UI 的访问地址（即使服务未启动，也基于配置端口拼接）。
 */
export function WebURL(): $CancellablePromise<string> {
    return $Call.ByID(14751362);
}

// Private type creation functions
const $$createType0 = channelpreset$0.CreateChannelResult.createFrom;
const $$createType1 = editor$0.Editor.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = configservice$0.AgentConfigStatus.createFrom;
const $$createType4 = $models.EnvFileState.createFrom;
const $$createType5 = $Create.Array($Create.Any);
const $$createType6 = configservice$0.ProviderKeyAsset.createFrom;
const $$createType7 = $Create.Array($$createType6);
const $$createType8 = channelpreset$0.ProviderPreset.createFrom;
const $$createType9 = $Create.Array($$createType8);
const $$createType10 = $Create.Map($Create.Any, $Create.Any);
const $$createType11 = backend$0.Status.createFrom;
const $$createType12 = $models.VersionInfo.createFrom;
const $$createType13 = configservice$0.ConfigDiffResult.createFrom;
