// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as backend$0 from "./internal/backend/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as channelpreset$0 from "./internal/channelpreset/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as configservice$0 from "./internal/configservice/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as editor$0 from "./internal/editor/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * @param {configservice$0.ApplyAgentConfigRequest} req
 * @returns {$CancellablePromise<void>}
 */
export function ApplyAgentConfig(req) {
    return $Call.ByID(1194974726, req);
}

/**
 * CancelUpdate 中止正在进行的下载/安装。
 * @returns {$CancellablePromise<void>}
 */
export function CancelUpdate() {
    return $Call.ByID(4179813658);
}

/**
 * CheckUpdate 查询是否有新版本可用。
 * @returns {$CancellablePromise<$models.UpdateInfo>}
 */
export function CheckUpdate() {
    return $Call.ByID(3715642294).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * CopyText 把文本写入系统剪贴板。
 * @param {string} text
 * @returns {$CancellablePromise<void>}
 */
export function CopyText(text) {
    return $Call.ByID(2418202931, text);
}

/**
 * @param {channelpreset$0.CreateChannelRequest} req
 * @returns {$CancellablePromise<channelpreset$0.CreateChannelResult>}
 */
export function CreateCCXChannelFromPreset(req) {
    return $Call.ByID(3922694447, req).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * DetectEditors 返回系统上可用的文本编辑器列表。
 * @returns {$CancellablePromise<editor$0.Editor[]>}
 */
export function DetectEditors() {
    return $Call.ByID(1308494416).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * DownloadAndInstall 下载、校验并触发安装。整个流程通过 update:progress 事件推送进度。
 * @param {$models.UpdateInfo} info
 * @returns {$CancellablePromise<void>}
 */
export function DownloadAndInstall(info) {
    return $Call.ByID(1836127345, info);
}

/**
 * GenerateProxyAccessKey 仅生成预览密钥，不写入任何文件。
 * @returns {$CancellablePromise<string>}
 */
export function GenerateProxyAccessKey() {
    return $Call.ByID(1874658839);
}

/**
 * @param {string} platform
 * @returns {$CancellablePromise<configservice$0.AgentConfigStatus>}
 */
export function GetAgentConfigStatus(platform) {
    return $Call.ByID(3013260948, platform).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * @returns {$CancellablePromise<boolean>}
 */
export function GetAutostartStatus() {
    return $Call.ByID(1022089850);
}

/**
 * @returns {$CancellablePromise<$models.EnvFileState>}
 */
export function GetEnvFile() {
    return $Call.ByID(4130444060).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * @returns {$CancellablePromise<string[]>}
 */
export function GetLogs() {
    return $Call.ByID(1688970508).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType6($result);
    }));
}

/**
 * @returns {$CancellablePromise<configservice$0.ProviderKeyAsset[]>}
 */
export function GetProviderKeyAssets() {
    return $Call.ByID(1999783760).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType8($result);
    }));
}

/**
 * @param {string} target
 * @returns {$CancellablePromise<channelpreset$0.ProviderPreset[]>}
 */
export function GetProviderPresets(target) {
    return $Call.ByID(764436626, target).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType10($result);
    }));
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function GetProxyAccessKey() {
    return $Call.ByID(355938326);
}

/**
 * @returns {$CancellablePromise<{ [_ in string]?: string }>}
 */
export function GetSavedProviderKeys() {
    return $Call.ByID(2703245855).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType11($result);
    }));
}

/**
 * @returns {$CancellablePromise<backend$0.Status>}
 */
export function GetStatus() {
    return $Call.ByID(2036427713).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType12($result);
    }));
}

/**
 * GetVersion 返回构建时注入的版本信息。
 * @returns {$CancellablePromise<$models.VersionInfo>}
 */
export function GetVersion() {
    return $Call.ByID(3507009081).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType13($result);
    }));
}

/**
 * IsSetupComplete 判断是否已完成初始配置（PROXY_ACCESS_KEY 已存在）。
 * @returns {$CancellablePromise<boolean>}
 */
export function IsSetupComplete() {
    return $Call.ByID(375603581);
}

/**
 * OpenDirectory 在系统文件管理器中打开目录。
 * @param {string} dirPath
 * @returns {$CancellablePromise<void>}
 */
export function OpenDirectory(dirPath) {
    return $Call.ByID(2081295652, dirPath);
}

/**
 * OpenEnvFileInEditor 使用指定编辑器打开 .env 文件。
 * @param {string} editorPath
 * @returns {$CancellablePromise<void>}
 */
export function OpenEnvFileInEditor(editorPath) {
    return $Call.ByID(2255035236, editorPath);
}

/**
 * OpenFileInEditor 使用指定编辑器打开任意文件。
 * @param {string} editorPath
 * @param {string} filePath
 * @returns {$CancellablePromise<void>}
 */
export function OpenFileInEditor(editorPath, filePath) {
    return $Call.ByID(1960821709, editorPath, filePath);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function OpenWebUIInBrowser() {
    return $Call.ByID(2011844568);
}

/**
 * @param {configservice$0.ApplyAgentConfigRequest} req
 * @returns {$CancellablePromise<configservice$0.ConfigDiffResult>}
 */
export function PreviewAgentConfigDiff(req) {
    return $Call.ByID(2249637809, req).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType14($result);
    }));
}

/**
 * @param {string} platform
 * @returns {$CancellablePromise<configservice$0.ConfigDiffResult>}
 */
export function PreviewRestoreConfigDiff(platform) {
    return $Call.ByID(2382293170, platform).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType14($result);
    }));
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function RestartService() {
    return $Call.ByID(194936479);
}

/**
 * @param {string} platform
 * @returns {$CancellablePromise<void>}
 */
export function RestoreAgentConfig(platform) {
    return $Call.ByID(3544811620, platform);
}

/**
 * @param {string} content
 * @returns {$CancellablePromise<void>}
 */
export function SaveEnvFile(content) {
    return $Call.ByID(4266218857, content);
}

/**
 * @param {boolean} enabled
 * @returns {$CancellablePromise<void>}
 */
export function SetAutostart(enabled) {
    return $Call.ByID(3109129572, enabled);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function ShowAgentTab() {
    return $Call.ByID(978526812);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function ShowStatusTab() {
    return $Call.ByID(1026910485);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function ShowWebUITab() {
    return $Call.ByID(1839858715);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function Shutdown() {
    return $Call.ByID(3879395531);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function StartService() {
    return $Call.ByID(220274594);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function StopService() {
    return $Call.ByID(2326025444);
}

/**
 * WebURL 返回当前网关 Web UI 的访问地址（即使服务未启动，也基于配置端口拼接）。
 * @returns {$CancellablePromise<string>}
 */
export function WebURL() {
    return $Call.ByID(14751362);
}

// Private type creation functions
const $$createType0 = $models.UpdateInfo.createFrom;
const $$createType1 = channelpreset$0.CreateChannelResult.createFrom;
const $$createType2 = editor$0.Editor.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = configservice$0.AgentConfigStatus.createFrom;
const $$createType5 = $models.EnvFileState.createFrom;
const $$createType6 = $Create.Array($Create.Any);
const $$createType7 = configservice$0.ProviderKeyAsset.createFrom;
const $$createType8 = $Create.Array($$createType7);
const $$createType9 = channelpreset$0.ProviderPreset.createFrom;
const $$createType10 = $Create.Array($$createType9);
const $$createType11 = $Create.Map($Create.Any, $Create.Any);
const $$createType12 = backend$0.Status.createFrom;
const $$createType13 = $models.VersionInfo.createFrom;
const $$createType14 = configservice$0.ConfigDiffResult.createFrom;
