// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class EnvFileState {
    /**
     * Creates a new EnvFileState instance.
     * @param {Partial<EnvFileState>} [$$source = {}] - The source object to create the EnvFileState.
     */
    constructor($$source = {}) {
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (!("content" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["content"] = "";
        }
        if (!("exists" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["exists"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new EnvFileState instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {EnvFileState}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new EnvFileState(/** @type {Partial<EnvFileState>} */($$parsedSource));
    }
}

export class UpdateInfo {
    /**
     * Creates a new UpdateInfo instance.
     * @param {Partial<UpdateInfo>} [$$source = {}] - The source object to create the UpdateInfo.
     */
    constructor($$source = {}) {
        if (!("available" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["available"] = false;
        }
        if (!("currentVersion" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["currentVersion"] = "";
        }
        if (!("latestVersion" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["latestVersion"] = "";
        }
        if (!("notes" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["notes"] = "";
        }
        if (!("downloadUrl" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["downloadUrl"] = "";
        }
        if (!("sha256Url" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["sha256Url"] = "";
        }
        if (!("size" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["size"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UpdateInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {UpdateInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new UpdateInfo(/** @type {Partial<UpdateInfo>} */($$parsedSource));
    }
}

export class VersionInfo {
    /**
     * Creates a new VersionInfo instance.
     * @param {Partial<VersionInfo>} [$$source = {}] - The source object to create the VersionInfo.
     */
    constructor($$source = {}) {
        if (!("version" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["version"] = "";
        }
        if (!("buildTime" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["buildTime"] = "";
        }
        if (!("gitCommit" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["gitCommit"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new VersionInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {VersionInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new VersionInfo(/** @type {Partial<VersionInfo>} */($$parsedSource));
    }
}
