// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class EnvFileState {
    "path": string;
    "content": string;
    "exists": boolean;

    /** Creates a new EnvFileState instance. */
    constructor($$source: Partial<EnvFileState> = {}) {
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("content" in $$source)) {
            this["content"] = "";
        }
        if (!("exists" in $$source)) {
            this["exists"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new EnvFileState instance from a string or object.
     */
    static createFrom($$source: any = {}): EnvFileState {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new EnvFileState($$parsedSource as Partial<EnvFileState>);
    }
}

/**
 * FrontendErrorReport 描述桌面 WebView 前端上报的运行时错误。
 */
export class FrontendErrorReport {
    "source": string;
    "message": string;
    "stack": string;
    "url": string;
    "userAgent": string;

    /** Creates a new FrontendErrorReport instance. */
    constructor($$source: Partial<FrontendErrorReport> = {}) {
        if (!("source" in $$source)) {
            this["source"] = "";
        }
        if (!("message" in $$source)) {
            this["message"] = "";
        }
        if (!("stack" in $$source)) {
            this["stack"] = "";
        }
        if (!("url" in $$source)) {
            this["url"] = "";
        }
        if (!("userAgent" in $$source)) {
            this["userAgent"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FrontendErrorReport instance from a string or object.
     */
    static createFrom($$source: any = {}): FrontendErrorReport {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new FrontendErrorReport($$parsedSource as Partial<FrontendErrorReport>);
    }
}

/**
 * LanguagePreference 描述桌面语言最终选择和原始系统语言。
 */
export class LanguagePreference {
    "locale": string;
    "manual": boolean;
    "systemLocale": string;

    /** Creates a new LanguagePreference instance. */
    constructor($$source: Partial<LanguagePreference> = {}) {
        if (!("locale" in $$source)) {
            this["locale"] = "";
        }
        if (!("manual" in $$source)) {
            this["manual"] = false;
        }
        if (!("systemLocale" in $$source)) {
            this["systemLocale"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LanguagePreference instance from a string or object.
     */
    static createFrom($$source: any = {}): LanguagePreference {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LanguagePreference($$parsedSource as Partial<LanguagePreference>);
    }
}

/**
 * ReleaseCheckResult 前端直接消费的版本检查结果。
 */
export class ReleaseCheckResult {
    "currentVersion": string;
    "latestVersion": string;
    "hasUpdate": boolean;
    "releaseUrl": string;

    /**
     * "latest" | "update-available" | "error"
     */
    "status": string;

    /** Creates a new ReleaseCheckResult instance. */
    constructor($$source: Partial<ReleaseCheckResult> = {}) {
        if (!("currentVersion" in $$source)) {
            this["currentVersion"] = "";
        }
        if (!("latestVersion" in $$source)) {
            this["latestVersion"] = "";
        }
        if (!("hasUpdate" in $$source)) {
            this["hasUpdate"] = false;
        }
        if (!("releaseUrl" in $$source)) {
            this["releaseUrl"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ReleaseCheckResult instance from a string or object.
     */
    static createFrom($$source: any = {}): ReleaseCheckResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ReleaseCheckResult($$parsedSource as Partial<ReleaseCheckResult>);
    }
}

export class VersionInfo {
    "version": string;
    "buildTime": string;
    "gitCommit": string;
    "distribution": string;

    /** Creates a new VersionInfo instance. */
    constructor($$source: Partial<VersionInfo> = {}) {
        if (!("version" in $$source)) {
            this["version"] = "";
        }
        if (!("buildTime" in $$source)) {
            this["buildTime"] = "";
        }
        if (!("gitCommit" in $$source)) {
            this["gitCommit"] = "";
        }
        if (!("distribution" in $$source)) {
            this["distribution"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new VersionInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): VersionInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new VersionInfo($$parsedSource as Partial<VersionInfo>);
    }
}
