<script setup lang="ts">
import { Textarea } from '@/components/ui/textarea'
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select'
import { Badge } from '@/components/ui/badge'
import { AlertCircle, CheckCircle2, Tag } from 'lucide-vue-next'
import { useLanguage } from '@/composables/useLanguage'

defineProps<{
  quickInput: string
  serviceType: string
  serviceTypeOptions: Array<{ label: string; value: string }>
  detectedBaseUrls: string[]
  detectedApiKeys: string[]
  expectedRequestUrls: Array<{ baseUrl: string; expectedUrl: string }>
  generatedChannelName: string
}>()

const emit = defineEmits<{
  (e: 'update:quick-input', value: string): void
  (e: 'update:service-type', value: string): void
  (e: 'quick-paste', text: string): void
}>()

const { tf } = useLanguage()
</script>

<template>
  <section class="space-y-4 p-6">
    <!-- 输入区域 -->
    <Textarea
      :model-value="quickInput"
      rows="10"
      class="!field-sizing-none min-h-[14rem] font-mono text-xs"
      :placeholder="tf('addChannel.quickInputPlaceholder', '粘贴配置片段，自动识别 Base URL 和 API Key（支持多行）\nhttps://api.example.com\nhttps://api-backup.example.com\nsk-ant-api03-xxxxxxxxxxxxxxxx\nsk-ant-api03-yyyyyyyyyyyyyyyy')"
      @update:model-value="(val) => emit('update:quick-input', val as string)"
      @paste="emit('quick-paste', $event.clipboardData?.getData('text/plain') || '')"
    />

    <!-- 检测结果 -->
    <div class="rounded-xl border border-border/60 bg-card/50 p-4">
      <div class="space-y-3">
        <!-- Base URLs（独占一行） -->
        <div class="space-y-2 rounded-lg border border-border bg-background/70 p-3">
          <div class="flex items-center gap-2 text-xs font-semibold">
            <CheckCircle2 v-if="detectedBaseUrls.length" class="h-4 w-4 text-emerald-500" />
            <AlertCircle v-else class="h-4 w-4 text-muted-foreground" />
            Base URLs
          </div>
          <template v-if="detectedBaseUrls.length">
            <div v-for="item in expectedRequestUrls" :key="item.baseUrl" class="space-y-0.5">
              <p class="truncate text-[11px] font-medium text-emerald-600">{{ item.baseUrl }}</p>
              <p class="truncate text-[10px] text-muted-foreground">
                {{ tf('addChannel.expectedRequest', '预期请求') }}: {{ item.expectedUrl }}
              </p>
            </div>
          </template>
          <p v-else class="text-xs text-muted-foreground">
            {{ tf('addChannel.noneDetected', '未识别到 URL') }}
          </p>
        </div>

        <!-- 两栏：左（渠道名称+上游类型）右（API Keys） -->
        <div class="grid gap-3 md:grid-cols-2">
          <!-- 左栏 -->
          <div class="space-y-3">
            <!-- 渠道名称预览 -->
            <div class="flex items-center gap-3 rounded-lg border-0 bg-muted/30 p-3">
              <Tag class="h-4 w-4 shrink-0 text-primary" />
              <div class="min-w-0 flex-1 space-y-0.5">
                <div class="text-[11px] text-muted-foreground">{{ tf('addChannel.channelName', '渠道名称') }}</div>
                <p class="truncate text-xs font-semibold text-primary">{{ generatedChannelName }}</p>
              </div>
              <Badge variant="secondary" class="shrink-0 text-[9px]">
                {{ tf('common.autoGenerated', '自动生成') }}
              </Badge>
            </div>

            <!-- 上游类型选择器 -->
            <div class="flex items-center gap-3 rounded-lg border-0 bg-muted/30 p-3">
              <component :is="'svg'" xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="h-4 w-4 shrink-0 text-muted-foreground">
                <path d="M12 2L2 7l10 5 10-5-10-5z" />
                <path d="M2 17l10 5 10-5" />
                <path d="M2 12l10 5 10-5" />
              </component>
              <div class="min-w-0 flex-1 space-y-1">
                <div class="text-[11px] text-muted-foreground">
                  {{ tf('channelEditor.basic.serviceType.label', '上游类型') }}
                </div>
                <Select :model-value="serviceType" @update:model-value="(val) => emit('update:service-type', String(val))">
                  <SelectTrigger class="h-7 border-0 bg-transparent p-0 shadow-none focus:ring-0">
                    <SelectValue :placeholder="tf('channelEditor.basic.serviceType.placeholder', '选择类型')" class="text-xs font-medium" />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem v-for="opt in serviceTypeOptions" :key="opt.value" :value="opt.value">
                      {{ opt.label }}
                    </SelectItem>
                  </SelectContent>
                </Select>
              </div>
            </div>
          </div>

          <!-- 右栏：API Keys -->
          <div class="space-y-2 rounded-lg border border-border bg-background/70 p-3">
            <div class="flex items-center gap-2 text-xs font-semibold">
              <CheckCircle2 v-if="detectedApiKeys.length" class="h-4 w-4 text-emerald-500" />
              <AlertCircle v-else class="h-4 w-4 text-muted-foreground" />
              {{ tf('channelEditor.auth.keys.label', 'API Keys') }}
            </div>
            <p v-if="detectedApiKeys.length" class="text-xs font-medium text-emerald-600">
              {{ detectedApiKeys.length }} {{ tf('channelCard.configuredKeys', 'active keys') }}
            </p>
            <p v-else class="text-xs text-muted-foreground">
              {{ tf('addChannel.noneDetected', '未识别到密钥') }}
            </p>
          </div>
        </div>
      </div>
    </div>
  </section>
</template>
