<script setup lang="ts">
import { Textarea } from '@/components/ui/textarea'
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select'
import { Badge } from '@/components/ui/badge'
import { AlertCircle, CheckCircle2, Layers, Tag } from 'lucide-vue-next'
import { useLanguage } from '@/composables/useLanguage'

defineProps<{
  quickInput: string
  serviceType: string
  serviceTypeOptions: Array<{ label: string; value: string }>
  detectedBaseUrls: string[]
  detectedApiKeys: string[]
  expectedRequestUrls: Array<{ baseUrl: string; expectedUrl: string }>
  generatedChannelName: string
}>()

const emit = defineEmits<{
  (e: 'update:quick-input', value: string): void
  (e: 'update:service-type', value: string): void
  (e: 'quick-paste', text: string): void
}>()

const { t } = useLanguage()
</script>

<template>
  <section class="space-y-4 p-6">
    <!-- 输入区域 -->
    <Textarea
      :model-value="quickInput"
      rows="10"
      class="!field-sizing-none min-h-[14rem] font-mono text-xs"
      :placeholder="t('addChannel.quickInputPlaceholder')"
      @update:model-value="(val) => emit('update:quick-input', val as string)"
      @paste="emit('quick-paste', $event.clipboardData?.getData('text/plain') || '')"
    />

    <!-- 检测结果 -->
    <div class="rounded-xl border border-border/60 p-4">
      <div class="space-y-3">
        <!-- Base URLs（独占一行） -->
        <div class="space-y-2 rounded-lg border border-border bg-background/70 p-3">
          <div class="flex items-center gap-2 text-xs font-semibold">
            <CheckCircle2 v-if="detectedBaseUrls.length" class="h-4 w-4 text-emerald-500" />
            <AlertCircle v-else class="h-4 w-4 text-muted-foreground" />
            Base URLs
          </div>
          <template v-if="detectedBaseUrls.length">
            <div v-for="item in expectedRequestUrls" :key="item.baseUrl" class="space-y-0.5">
              <p class="truncate text-[11px] font-medium text-emerald-600">{{ item.baseUrl }}</p>
              <p class="truncate text-[10px] text-muted-foreground">
                {{ t('addChannel.expectedRequest') }}: {{ item.expectedUrl }}
              </p>
            </div>
          </template>
          <p v-else class="text-xs text-muted-foreground">
            {{ t('addChannel.noneDetected') }}
          </p>
        </div>

        <!-- 两栏：左（渠道名称+上游类型）右（API Keys） -->
        <div class="grid items-start gap-3 md:grid-cols-12">
          <!-- 左栏：7/12 -->
          <div class="space-y-3 md:col-span-7">
            <!-- 渠道名称预览 -->
            <div class="flex items-center gap-3 rounded-lg border-0 bg-muted/10 p-3">
              <Tag class="h-4 w-4 shrink-0 text-primary" />
              <div class="min-w-0 flex-1 space-y-0.5">
                <div class="text-[11px] text-muted-foreground">{{ t('addChannel.channelName') }}</div>
                <p class="text-xs font-semibold text-primary break-all">{{ generatedChannelName }}</p>
              </div>
              <Badge variant="secondary" class="shrink-0 text-[9px]">
                {{ t('common.autoGenerated') }}
              </Badge>
            </div>

            <!-- 上游类型选择器 -->
            <div class="flex items-center gap-3 rounded-lg border-0 bg-muted/10 p-3">
              <Layers class="h-4 w-4 shrink-0 text-muted-foreground" />
              <div class="min-w-0 flex-1 text-[11px] text-muted-foreground">
                {{ t('channelEditor.basic.serviceType.label') }}
              </div>
              <Select :model-value="serviceType" @update:model-value="(val) => emit('update:service-type', String(val))">
                <SelectTrigger class="h-7 w-[160px] border-0 bg-transparent p-0 shadow-none focus:ring-0">
                  <SelectValue :placeholder="t('channelEditor.basic.serviceType.placeholder')" class="text-xs font-medium" />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem v-for="opt in serviceTypeOptions" :key="opt.value" :value="opt.value">
                    {{ opt.label }}
                  </SelectItem>
                </SelectContent>
              </Select>
            </div>
          </div>

          <!-- 右栏：API Keys（5/12） -->
          <div class="rounded-lg border border-border bg-background/70 p-3 md:col-span-5">
            <div class="flex items-center gap-2 text-xs font-semibold mb-1.5">
              <CheckCircle2 v-if="detectedApiKeys.length" class="h-4 w-4 text-emerald-500" />
              <AlertCircle v-else class="h-4 w-4 text-muted-foreground" />
              {{ t('addChannel.apiKeys') }}
            </div>
            <p v-if="detectedApiKeys.length" class="text-xs text-emerald-600">
              {{ t('addChannel.detectedKeys', { count: String(detectedApiKeys.length) }) }}
            </p>
            <p v-else class="text-xs text-muted-foreground">
              {{ t('addChannel.enterApiKey') }}
            </p>
          </div>
        </div>
      </div>
    </div>
  </section>
</template>
