package channelpreset

// Code generated by scripts/generate-channel-presets.mjs; DO NOT EDIT.

func generatedClaudeMessagesTargetConfigs() map[string]channelTargetConfig {
	return map[string]channelTargetConfig{
		"deepseek":     channelTargetConfig{ModelMapping: map[string]string{"fable": "deepseek-v4-pro", "haiku": "deepseek-v4-flash", "opus": "deepseek-v4-pro", "sonnet": "deepseek-v4-pro"}, ReasoningParamStyle: "reasoning", PassbackReasoningContent: true, PassbackThinkingBlocks: true, NoVision: true, StripEmptyTextBlocks: true, StripImageGenerationTool: true},
		"mimo":         channelTargetConfig{ModelMapping: map[string]string{"fable": "mimo-v2.5-pro", "haiku": "mimo-v2.5-pro", "opus": "mimo-v2.5-pro", "sonnet": "mimo-v2.5-pro"}, ReasoningParamStyle: "reasoning", PassbackReasoningContent: true, NoVisionModels: []string{"mimo-v2.5-pro"}, VisionFallbackModel: "mimo-v2.5", RateLimitRPM: 80},
		"compshare":    channelTargetConfig{ModelMapping: map[string]string{"fable": "glm-5.2", "haiku": "deepseek-v4-flash", "opus": "glm-5.2", "sonnet": "glm-5.2"}, ReasoningMapping: map[string]string{"MiniMax-M2.7": "xhigh", "fable": "max", "haiku": "high", "opus": "max", "sonnet": "max"}, ReasoningParamStyle: "reasoning", PassbackReasoningContent: true, PassbackThinkingBlocks: true, NoVisionModels: []string{"glm-5.2", "deepseek-v4-flash"}, VisionFallbackModel: "MiniMax-M2.7", StripEmptyTextBlocks: true},
		"runapi":       channelTargetConfig{},
		"unity2":       channelTargetConfig{},
		"kimi":         channelTargetConfig{ModelMapping: map[string]string{"fable": "kimi-k2.6", "haiku": "kimi-k2.6", "opus": "kimi-k2.6", "sonnet": "kimi-k2.6"}},
		"glm":          channelTargetConfig{ModelMapping: map[string]string{"fable": "glm-5.2", "haiku": "glm-5.2", "opus": "glm-5.2", "sonnet": "glm-5.2"}},
		"minimax":      channelTargetConfig{ModelMapping: map[string]string{"fable": "MiniMax-M3", "haiku": "MiniMax-M2.7", "opus": "MiniMax-M3", "sonnet": "MiniMax-M3"}, PassbackReasoningContent: true, NoVision: true},
		"dashscope":    channelTargetConfig{ModelMapping: map[string]string{"fable": "glm-5.2", "haiku": "glm-5.2", "opus": "glm-5.2", "sonnet": "glm-5.2"}},
		"opencode-zen": channelTargetConfig{ModelMapping: map[string]string{"fable": "glm-5.2", "haiku": "deepseek-v4-flash", "opus": "glm-5.2", "sonnet": "glm-5.2"}, ReasoningMapping: map[string]string{"fable": "max", "haiku": "high", "opus": "max", "sonnet": "max"}},
		"opencode-go":  channelTargetConfig{ModelMapping: map[string]string{"fable": "glm-5.2", "haiku": "deepseek-v4-flash", "opus": "glm-5.2", "sonnet": "glm-5.2"}, ReasoningMapping: map[string]string{"fable": "max", "haiku": "high", "opus": "max", "sonnet": "max"}},
		"modelscope":   channelTargetConfig{ModelMapping: map[string]string{"fable": "ZhipuAI/GLM-5.2", "haiku": "deepseek-ai/DeepSeek-V4-Flash", "opus": "ZhipuAI/GLM-5.2", "sonnet": "ZhipuAI/GLM-5.2"}, NoVisionModels: []string{"deepseek-ai/DeepSeek-V4-Flash"}, VisionFallbackModel: "MiniMax/MiniMax-M2.7"},
		"volc-ark":     channelTargetConfig{ModelMapping: map[string]string{"fable": "glm-5.2", "haiku": "deepseek-v4-flash", "opus": "glm-5.2", "sonnet": "glm-5.2"}, ReasoningMapping: map[string]string{"fable": "max", "haiku": "high", "opus": "max", "sonnet": "max", "minimax-m3": "xhigh"}, ReasoningParamStyle: "reasoning", PassbackReasoningContent: true, PassbackThinkingBlocks: true, NoVisionModels: []string{"glm-5.2", "deepseek-v4-flash"}, VisionFallbackModel: "minimax-m3"},
		"qianfan":      channelTargetConfig{ModelMapping: map[string]string{"fable": "qianfan-code-latest", "haiku": "qianfan-code-latest", "opus": "qianfan-code-latest", "sonnet": "qianfan-code-latest"}},
		"xfyun":        channelTargetConfig{},
	}
}
